# Generated by Django 4.0.4 on 2022-05-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postportfolio',
            name='urltoproject',
            field=models.CharField(max_length=255),
        ),
    ]
